name: Test Steps Output
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - id: release
              run: echo "packages/config-array--release_created=true" >> "$GITHUB_OUTPUT"

            
            - run: echo result from steps ${{ steps.release.outputs['packages/config-array--release_created'] }}            

            
            - env:
                STEPS_RELEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
              run: echo result from env $STEPS_RELEASE_OUTPUTS

            - env:
                STEPS_RELEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
              run: ls ; node test.js

            - run: echo result from something else $DEBIAN_FRONTEND
